Repository mulesoft/docs-mule-runtime, pull requests merged in 2019-08, with the labels that each got.

#675 Add 'sources-reference.adoc' as page-alias of 'redelivery-policy.adoc'
  modules/ROOT/pages/redelivery-policy.adoc
Labels: DO NOT MERGE YET

#711 DOCS-4572-4.2-enterprise-patterns-editing-kt
  modules/ROOT/pages/understanding-enterprise-integration-patterns-using-mule.adoc
Labels: DO NOT MERGE YET

#727 DOCS-5679-4.1-remove-SLA-external-link-kt
  modules/ROOT/pages/hadr-guide.adoc
Labels: copied_to_4.2

#733 Added section for creating a lightweight package.
  modules/ROOT/pages/mmp-concept.adoc
Labels: copied_to_4.2

#729 DOCS-5366-4.1-recommended-software-update-kt
  modules/ROOT/pages/hardware-and-software-requirements.adoc
Labels: copied_to_4.2

#747 DOCS-5180-4.2-deploying-profiling-link-kt
  modules/ROOT/pages/deploying.adoc
Labels: DO NOT MERGE YET

#746 DOCS-5180-4.1-deploying-profiling-link-kt
  modules/ROOT/pages/deploying.adoc
Labels: DO NOT MERGE YET, copied_to_4.2

#759 redirect for removed topic from getting-started
  modules/ROOT/pages/choice-router-concept.adoc
Labels: DO NOT MERGE YET

#769 page alias for out of date topic DO NOT MERGE
  modules/ROOT/pages/intro-mule-message.adoc
Labels: DO NOT MERGE YET

#770 Remove links to outdated topic DO NOT MERGE
  modules/ROOT/pages/mule-expression-language-mel.adoc
Labels: DO NOT MERGE YET

#771 remove outdated links DO NOT MERGE
  modules/ROOT/pages/mule-expression-language-examples.adoc
  modules/ROOT/pages/mule-expression-language-mel.adoc
Labels: DO NOT MERGE YET

#772 Remote outdated links DO NOT MERGE
  modules/ROOT/pages/mule-expression-language-basic-syntax.adoc
  modules/ROOT/pages/mule-expression-language-examples.adoc
  modules/ROOT/pages/mule-expression-language-mel.adoc
Labels: DO NOT MERGE YET

#776 Remove outdated link DO NOT MERGE
  modules/ROOT/pages/mule-expression-language-basic-syntax.adoc
  modules/ROOT/pages/mule-expression-language-examples.adoc
  modules/ROOT/pages/mule-expression-language-mel.adoc
Labels: DO NOT MERGE YET

#777 Remove outdated links DO NOT MERGE
  modules/ROOT/pages/mule-expression-language-basic-syntax.adoc
  modules/ROOT/pages/mule-expression-language-examples.adoc
  modules/ROOT/pages/mule-expression-language-mel.adoc
Labels: DO NOT MERGE YET
