Repository mulesoft/docs-mule-runtime, pull requests merged in 2019-09, with the labels that each got.

#819 Bringing updates from PR #817.
  modules/ROOT/pages/secure-configuration-properties.adoc
Labels: copied_to_4.2

#803 Remove unfinished MUnit migration information
  modules/ROOT/pages/_partials/nav-migration.adoc
  modules/ROOT/pages/index-migration.adoc
  modules/ROOT/pages/migration-cheat-sheet.adoc
  modules/ROOT/pages/migration-munit-assert-processor-changes.adoc
  modules/ROOT/pages/migration-munit-mock-processor-changes.adoc
  modules/ROOT/pages/migration-munit.adoc
Labels: DO NOT MERGE YET

#804 Remove unfinished MUnit migration information
  modules/ROOT/pages/_partials/nav-migration.adoc
  modules/ROOT/pages/index-migration.adoc
  modules/ROOT/pages/migration-cheat-sheet.adoc
  modules/ROOT/pages/migration-munit-assert-processor-changes.adoc
  modules/ROOT/pages/migration-munit-mock-processor-changes.adoc
  modules/ROOT/pages/migration-munit.adoc
Labels: DO NOT MERGE YET

#835 Docs 5889 mule message v4.1
  modules/ROOT/pages/about-mule-message.adoc
Labels: copied_to_4.2

#838 Docs 5438 crypto sign v4.1
  modules/ROOT/pages/cryptography-pgp.adoc
Labels: copied_to_4.2

#836 Docs 5517 mmp sync v4.1
  modules/ROOT/pages/mmp-concept.adoc
Labels: copied_to_4.2

#840 Docs 5222 mmp domain v4.2
  modules/ROOT/pages/mmp-concept.adoc
Labels: DO NOT MERGE YET

#850 DOCS 5222 - Applying changes from PR #840
  modules/ROOT/pages/mmp-concept.adoc
Labels: copied_to_4.2

#820 Update mongodb-connector.adoc
  modules/ROOT/pages/mongodb-connector.adoc
Labels: 3.x Connector

#810 update amazon-sns-user-manual
  modules/ROOT/pages/amazon-sns-connector.adoc
Labels: 3.x Connector
