Repository mulesoft/docs-mule-runtime, pull requests merged in 2021-10, with the labels that each got.

#2060 DOCS-11763-3.7-remove-dw-docs-kt
  modules/ROOT/nav.adoc
  modules/ROOT/pages/dataweave-examples.adoc
  modules/ROOT/pages/dataweave-migrator.adoc
  modules/ROOT/pages/dataweave-reference-documentation.adoc
  modules/ROOT/pages/dataweave-streaming.adoc
  modules/ROOT/pages/dataweave-tutorial.adoc
  modules/ROOT/pages/dataweave.adoc
Labels: DO NOT MERGE (YET)

#1960 DOCS-11207-feature-flags-v4.4-cv
  modules/ROOT/pages/_partials/nav-app-dev.adoc
  modules/ROOT/pages/feature-flagging.adoc
Labels: DO NOT MERGE (YET), Mule

#2080 Update dw-operators.adoc
  modules/ROOT/pages/dw-operators.adoc
Labels: cla:signed

#2077 Update dataweave-selectors.adoc
  modules/ROOT/pages/dataweave-selectors.adoc
Labels: cla:signed

#2079 Docs 11763 3.7 remove dw docs take2 duke
  modules/ROOT/nav.adoc
  modules/ROOT/pages/dataweave-examples.adoc
  modules/ROOT/pages/dataweave-migrator.adoc
  modules/ROOT/pages/dataweave-reference-documentation.adoc
  modules/ROOT/pages/dataweave-streaming.adoc
  modules/ROOT/pages/dataweave-tutorial.adoc
  modules/ROOT/pages/dataweave.adoc
Labels: DO NOT MERGE (YET)

#2062 DOCS-12312: example is using query param, not URL param (Mule 4.3)
  modules/ROOT/pages/idempotent-message-validator.adoc
Labels: cla:signed

#2033 DOCS-11970 link to upgrade update docs duke
  modules/ROOT/nav.adoc
  modules/ROOT/pages/_partials/upgrade-update-migrate-mule.adoc
  modules/ROOT/pages/index.adoc
  modules/ROOT/pages/runtime-installation-task.adoc
Labels: DO NOT MERGE (YET), Mule

#2098 Docs 11482 batch serialization error duke
  modules/ROOT/pages/batch-filters-and-batch-aggregator.adoc
Labels: cla:missing
